### PR TITLE
Added Optional Redirect URI for OAuth Clients that require specific Redirect URIs

### PR DESCRIPTION
**Pull request by DeekyJay**

### CODE REVIEW

**Comment by DeekyJay** [comment]
Jumped the gun too soon, I will have more changes.

**Comment by mawie81** [comment]
Thanks for the PR 👍 
Before looking at this could you please check the parameter name again?
The readme says `redirectUri` but the code uses `redirect_uri`. Would prefer `redirectUri` for the option.

And could you please stash the commits into one?

Thanks 😄

**Comment by DeekyJay** [comment]
Hey! Fixed the issue and rebased. Not sure why there is a conflict though.

**Comment by mawie81** [comment]
Thanks 😄 
Just landed and published as 2.2.0

**Comment by DeekyJay** [comment]
Awesome! :smile:

**Pull request closed without merging**
